### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by ajhofferber** [nicscholz/C4#1]
Hi Nic,

Good work on your unit one project! I really like the theme that you added to the traditional connect 4 game.  Your scripts code is really well organized.  It is nice to see that you broke different pieces down into different files and brought them all together, it makes it really easy to understand what each part of your code is responsible for. 

Don't forget to add a markdown to your project.  Having a README.md file is really important as you move on and you want people to be able to understand what you've made in your projects, as well as include a link so that they can go to your actual site.

Overall, you game has a nice UI and plays really well. 

Project score: 2 (refer to project markdown for scoring rubric)

-Ash

**Comment by Avizacherman** [comment]
Nic,

I really like that you solved the win condition algorithmically. It's really important as you code to avoid 'hardcoding' whenever you can, because you never know what edge cases might occur. Your javascript is great. I agree with Ash as well, the UI is really nice and the game plays really well. Great work!

-Avi
